package com.project.post;

public enum PostCategory {
	UNCATEGORIZED, ABSTRACT, AERIAL, ANIMALS, BLACKANDWHITE, BOUDOIR, CELEBRITIES, CITYANDARCHITECTURE,
	COMMERCIAL, CONCERT, FAMILY, FASHION, FILM, FINEART, FOOD, JOURNALISM, LANDSCAPES,
	MACRO, NATURE, NIGHT, NUDE, PEOPLE, PERFORMINGARTS, SPORT, STILLLIFE, STREET, TRANSPORTATION, 
	TRAVEL, UNDERWATER, URBANEXPLORATION, WEDDING;
}
